### ISSUE TITLE
How run paperless without encryption

### ISSUE THREAD

**Issue by erikarvstedt** [erikarvstedt/unencrypted-paperless#1]
1. Use the Paperless version from [this branch](https://github.com/erikarvstedt/paperless/tree/ea-disable-encryption)
2. When running paperless, set the environment variable `PAPERLESS_STORAGE_TYPE=unencrypted`

**Comment by GarethFox** [comment]
SupaGreat!
Plus your branch also has 'Account for KeyError problem in #345' patched!
I will give it a try asap and get back to you soon once the docker stack running using your environment variable.
Thanks a lot allowing us to access this feature!

**Comment by GarethFox** [comment]
Hi @erikarvstedt !
I am about to build a paperless stack based on your branch, I will add the environment variable 
`PAPERLESS_STORAGE_TYPE=unencrypted` in the `docker-compose.env` file as mentioned. Just one thing unclear, shall I define or delete the `PAPERLESS_PASSPHRASE=CHANGE_ME`? What would be the impact to define or remove that one regarding this new variable you set in your branch?
Thank you in advance,

**Comment by GarethFox** [comment]
For the moment, whatever I comment out or define the `PAPERLESS_PASSPHRASE=CHANGE_ME` variable I have a error message trying to build up the app using `docker-compose`
```
ERROR: for paper-back-ep  Container "c018c63a8bfc" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by erikarvstedt** [comment]
If you want to create a new database with encryption disabled, just define `PAPERLESS_STORAGE_TYPE=unencrypted` in `docker-compose.env`.
`PAPERLESS_PASSPHRASE` is only needed if there are still encrypted docs in your database.

To get rid of the error message, try deleting the container (`docker kill c018c63a8bfc; docker rm c018c63a8bfc`) and re-run `docker compose up`.

**Comment by GarethFox** [comment]
okay, I tried again building from your branch from scratch within my docker-compose stack.
I reuse a configuration working in an other server currently based on master branch.
Here is what I use for building your repo.
`docker-compose.env`:
```
PAPERLESS_STORAGE_TYPE=unencrypted
PAPERLESS_OCR_LANGUAGES=fra deu eng
DJANGO_LOG_LEVEL=DEBUG
```
`docker-compose.yml`
```
version: '2.1'

services:
# PUBLIC web proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/nginx/html:/usr/share/nginx/html
      - /docker/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend

# PUBLIC cert manager
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - /docker/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - frontend

# PUBLIC paper-app
  paper-app:
    build:
      context: ./paperless/
      dockerfile: ./Dockerfile
    container_name: paper-app
    restart: unless-stopped
    expose:
      - '8000'
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /docker/paperless/data:/usr/src/paperless/data
      - /docker/paperless/media:/usr/src/paperless/media
    env_file: ./paperless/docker-compose.env
    environment:
      - VIRTUAL_HOST=paper.local
    command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]
    networks:
      - frontend
      - backend

# PRIVATE paper-back
  paper-back:
    build:
      context: ./paperless/
      dockerfile: ./Dockerfile
    container_name: paper-back
    restart: unless-stopped
    depends_on:
      paper-app:
        condition: service_healthy
    volumes:
      - /docker/paperless/data:/usr/src/paperless/data
      - /docker/paperless/media:/usr/src/paperless/media
      - /docker/paperless/consume:/consume
      - /docker/paperless/export:/export
    env_file: ./paperless/docker-compose.env
    command: ["document_consumer"]
    networks:
      - backend

networks:
  frontend:
  backend:
```
`docker-compose.yml` is in the parent folder of /paperless folder where can be find the repo sources I downloaded.

`docker kill` `docker rm` and re-up the stack does not change anything.
`docker ps -a` shows paper-app looping in restarting mode.
`docker-compose logs paper-app` returns nothing special.
I changed `command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]` by `command: ["/usr/src/paperless/src/manage.py", "runserver", "--insecure", "0.0.0.0:8000"]` after reading this issue https://github.com/danielquinn/paperless/issues/317
Then `docker-compose logs paper-app` returns:
```
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied
paper-app            | /sbin/docker-entrypoint.sh: line 106: /usr/src/paperless/src/manage.py: Permission denied

```
Basically I can't have an healthy paper-app, then docker can't mount the paper-back.

**Comment by erikarvstedt** [comment]
Sorry, I can't help you with your specific setup.

But let's try this:
I've created a simple docker-compose config that's guaranteed to work:
- Checkout [this branch](https://github.com/erikarvstedt/paperless/tree/docker-cfg-no-encryption).
- Run `docker-compose up` from the repo root dir.
  All user data is stored in `./run`. The consume directory is `./run/consume`.

Now try to modifiy this config to fit your particular needs.

**Comment by GarethFox** [comment]
Thanks a lot.
Seems that I can have healthy paperless stack on a minimalist environment with proxy+ssl manager, but can't have healthy webapp container on more complex stacks containing more apps+db's.
I wonder why it generates conflict in complex stacks whereas it seems to work on more simple ones...

**Comment by GarethFox** [comment]
Here is as far as I could get in the debug.
I have now a steady docker-compose.yml containing my full stack plus paperless.
Paperless part is the following: 
```
# PUBLIC paper-app
  paper-app:
    build:
      context: ./paperless/
      dockerfile: ./Dockerfile
    container_name: paper-app
    restart: unless-stopped
    expose:
      - '8000'
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - /docker/paperless/data:/usr/src/paperless/data
      - /docker/paperless/media:/usr/src/paperless/media
    env_file: ./paperless/docker-compose.env
    environment:
      - VIRTUAL_HOST=paper.example.com
      - LETSENCRYPT_HOST=paper.example.com
      - LETSENCRYPT_EMAIL=admin@example.com
      - REUSE_PRIVATE_KEYS=true
      - PAPERLESS_OCR_LANGUAGES=
    command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]
    networks:
      public:
      private:
        ipv4_address: 172.200.0.16

# PRIVATE paper-back
  paper-back:
    build:
      context: ./paperless/
      dockerfile: ./Dockerfile
    container_name: paper-back
    restart: unless-stopped
    depends_on:
      paper-app:
        condition: service_healthy
    volumes:
      - /docker/paperless/data:/usr/src/paperless/data
      - /docker/paperless/media:/usr/src/paperless/media
      - /home/user/paperless/consume:/consume
      - /docker/paperless/export:/export
    env_file: ./paperless/docker-compose.env
    command: ["document_consumer"]
    networks:
      private:
        ipv4_address: 172.200.0.17
```
Then, in the folder containing the `docker-compose.yml` file, I clone the first branch you mentioned `git clone https://github.com/erikarvstedt/paperless.git`.
Result is:
```
ERROR: for paper-back  Container "475fffdc615b" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
Then I tried with your last branch mentioned `git clone https://github.com/erikarvstedt/paperless.git -b docker-cfg-no-encryption`. (just commented `PAPERLESS_DISABLE_LOGIN=true` in `.env` file)
Result is:
```
ERROR: for paper-back  Container "7f7d47d4b540" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
Finally I redo the test cloning the original-master `git clone https://github.com/danielquinn/paperless.git`
Result is positive and all the stack is working with healthy paperless stack.

I am afraid I am not able to use your branch straight away to enjoy no encryption file storage...
